apiVersion: v1
kind: Service
metadata:
  name: quietplaces-service
  labels:
    app: quietplaces
spec:
  type: NodePort
  selector:
    app: quietplaces
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
